blueprint:
  name: Notifications SMS - Rallumage après délai configurable
  description: Désactive le boolean et le rallume après un délai personnalisé.
  domain: automation
  input:
    cible_boolean:
      name: Boolean de notification
      description: Le boolean à réactiver
      selector:
        entity:
          domain: input_boolean
    heures:
      name: Heures de délai
      description: Entité `input_number` pour le nombre d'heures à attendre
      selector:
        entity:
          domain: input_number
    minutes:
      name: Minutes de délai
      description: Entité `input_number` pour le nombre de minutes à attendre
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input cible_boolean
    to: "off"

variables:
  heures: "{{ states(!input 'heures') | float(0) }}"
  minutes: "{{ states(!input 'minutes') | float(0) }}"

condition: []

action:
  - delay:
      hours: "{{ heures | int }}"
      minutes: "{{ minutes | int }}"
  - service: input_boolean.turn_on
    target:
      entity_id: !input cible_boolean

mode: single
