blueprint:
  name: Notifications SMS - Rallumage après délai
  description: Rallume un input_boolean après un délai basé sur deux input_number.
  domain: automation
  input:
    cible_boolean:
      name: Entité boolean
      description: L'entité boolean à rallumer
      selector:
        entity:
          domain: input_boolean
    heures:
      name: Input number heures
      description: Entité input_number pour les heures
      selector:
        entity:
          domain: input_number
    minutes:
      name: Input number minutes
      description: Entité input_number pour les minutes
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input cible_boolean
    to: "off"

variables:
  delay_hours: "{{ states(!input 'heures') | float(0) }}"
  delay_minutes: "{{ states(!input 'minutes') | float(0) }}"

action:
  - delay:
      hours: "{{ delay_hours | int }}"
      minutes: "{{ delay_minutes | int }}"
  - service: input_boolean.turn_on
    target:
      entity_id: !input cible_boolean

mode: single
