blueprint:
  name: Test Notifications SMS - Blueprint basique
  description: Teste la réactivation d’un boolean après 1 minute
  domain: automation
  input:
    cible_boolean:
      name: Boolean à tester
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input cible_boolean
    to: "off"

action:
  - delay:
      minutes: 1
  - service: input_boolean.turn_on
    target:
      entity_id: !input cible_boolean

mode: single
