blueprint:
  name: Notifications SMS - Rallumage après délai
  description: Rallume un input_boolean après un délai basé sur deux input_number.
  domain: automation
  input:
    cible_boolean:
      name: Entité boolean
      description: Le boolean à rallumer
      selector:
        entity:
          domain: input_boolean
    heures:
      name: Input number heures
      description: Entité input_number pour les heures
      selector:
        entity:
          domain: input_number
    minutes:
      name: Input number minutes
      description: Entité input_number pour les minutes
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input cible_boolean
    to: "off"

action:
  - delay:
      hours: "{{ states[inputs.heures] | float(0) | int }}"
      minutes: "{{ states[inputs.minutes] | float(0) | int }}"
  - service: input_boolean.turn_on
    target:
      entity_id: !input cible_boolean

mode: single
